
export interface CompanyInfo {
    name: string;
    industry: string;
    description: string;
    tier: 'MNC' | 'Unicorn' | 'Startup' | 'Service-Based';
    logoUrl?: string;
}

export const INDIAN_COMPANIES: CompanyInfo[] = [
    // --- MNCs & Conglomerates ---
    { name: "Reliance Industries", industry: "Conglomerate", tier: "MNC", description: "Indian multinational conglomerate headquartered in Mumbai." },
    { name: "Tata Consultancy Services", industry: "IT Services", tier: "Service-Based", description: "Global leader in IT services, consulting, and business solutions." },
    { name: "Infosys", industry: "IT Services", tier: "Service-Based", description: "Global leader in next-generation digital services and consulting." },
    { name: "HDFC Bank", industry: "Banking", tier: "MNC", description: "India's largest private sector bank." },
    { name: "ICICI Bank", industry: "Banking", tier: "MNC", description: "Leading private sector bank in India." },
    { name: "Hindustan Unilever", industry: "FMCG", tier: "MNC", description: "India's largest fast-moving consumer goods company." },
    { name: "Bharti Airtel", industry: "Telecom", tier: "MNC", description: "Leading global telecommunications company." },
    { name: "Wipro", industry: "IT Services", tier: "Service-Based", description: "Leading technology services and consulting company." },
    { name: "HCL Technologies", industry: "IT Services", tier: "Service-Based", description: "Global technology company that helps enterprises reimagine their businesses." },
    { name: "Tech Mahindra", industry: "IT Services", tier: "Service-Based", description: "Offers innovative and customer-centric digital experiences." },
    { name: "Larsen & Toubro", industry: "Conglomerate", tier: "MNC", description: "Indian multinational engaged in EPC projects, hi-tech manufacturing and services." },
    { name: "Bajaj Finance", industry: "Fintech", tier: "MNC", description: "Indian non-banking financial company." },
    { name: "Asian Paints", industry: "Chemicals", tier: "MNC", description: "Indian multinational paint company." },
    { name: "Maruti Suzuki", industry: "Automotive", tier: "MNC", description: "India's largest car manufacturer." },
    { name: "Sun Pharma", industry: "Pharma", tier: "MNC", description: "Indian multinational pharmaceutical company." },
    { name: "Accenture", industry: "IT Services", tier: "MNC", description: "Fortune Global 500 company specializing in information technology services." },
    { name: "Capgemini", industry: "IT Services", tier: "MNC", description: "Global leader in partnering with companies to transform and manage their business." },
    { name: "Google", industry: "Tech", tier: "MNC", description: "American multinational technology company focusing on artificial intelligence." },
    { name: "Microsoft", industry: "Tech", tier: "MNC", description: "American multinational technology corporation." },
    { name: "Amazon", industry: "E-commerce", tier: "MNC", description: "American multinational technology company focusing on e-commerce." },

    // --- Product Giants & Late Stage ---
    { name: "Zoho", industry: "SaaS", tier: "MNC", description: "Indian multinational technology company that makes web-based business tools." },
    { name: "Freshworks", industry: "SaaS", tier: "MNC", description: "SaaS company that provides customer engagement software." },
    { name: "Flipkart", industry: "E-commerce", tier: "MNC", description: "India's leading e-commerce marketplace." },
    { name: "MakeMyTrip", industry: "Travel", tier: "MNC", description: "Indian online travel company." },
    { name: "Info Edge", industry: "Internet", tier: "MNC", description: "Pure play internet company (Naukri, Jeevansathi)." },
    { name: "Paytm", industry: "Fintech", tier: "Unicorn", description: "Indian multinational financial technology company." },
    { name: "Zomato", industry: "Food Tech", tier: "Unicorn", description: "Indian multinational restaurant aggregator and food delivery company." },
    { name: "Swiggy", industry: "Food Tech", tier: "Unicorn", description: "India's leading on-demand delivery platform." },
    { name: "PhonePe", industry: "Fintech", tier: "Unicorn", description: "Indian digital payments and financial services company." },

    // --- Unicorns (From Verified Data) ---
    { name: "Zerodha", industry: "Fintech", tier: "Unicorn", description: "Indian financial services company offers brokerage-free equity investments." },
    { name: "Razorpay", industry: "Fintech", tier: "Unicorn", description: "Payments solution in India that allows businesses to accept, process and disburse payments." },
    { name: "Cred", industry: "Fintech", tier: "Unicorn", description: "Members-only credit card bill payment platform." },
    { name: "Groww", industry: "Fintech", tier: "Unicorn", description: "Online investment platform." },
    { name: "Zepto", industry: "Quick Commerce", tier: "Unicorn", description: "Indian quick-commerce company that delivers groceries on demand." },
    { name: "Blinkit", industry: "Quick Commerce", tier: "Unicorn", description: "Instant delivery service." },
    { name: "Meesho", industry: "E-commerce", tier: "Unicorn", description: "Indian social commerce platform." },
    { name: "Lenskart", industry: "E-commerce", tier: "Unicorn", description: "Optical prescription eyewear retail chain." },
    { name: "Nykaa", industry: "E-commerce", tier: "Unicorn", description: "Indian e-commerce company, selling beauty, wellness and fashion products." },
    { name: "Postman", industry: "SaaS", tier: "Unicorn", description: "API platform for building and using APIs." },
    { name: "BrowserStack", industry: "SaaS", tier: "Unicorn", description: "Cloud web and mobile testing platform." },
    { name: "Unacademy", industry: "EdTech", tier: "Unicorn", description: "Indian educational technology company." },
    { name: "PhysicsWallah", industry: "EdTech", tier: "Unicorn", description: "Indian educational technology company." },
    { name: "Urban Company", industry: "Services", tier: "Unicorn", description: "Gig marketplace for home services." },
    { name: "Cars24", industry: "Auto Tech", tier: "Unicorn", description: "Tech-enabled used car disruptor." },
    { name: "NoBroker", industry: "Real Estate", tier: "Unicorn", description: "Real estate platform connecting owners and tenants." },
    { name: "Dream11", industry: "Gaming", tier: "Unicorn", description: "Fantasy sports platform." },
    { name: "Games24x7", industry: "Gaming", tier: "Unicorn", description: "Online gaming company." },
    { name: "OfBusiness", industry: "B2B", tier: "Unicorn", description: "Tech-enabled platform for SME raw material procurement." },
    { name: "Licious", industry: "Food Tech", tier: "Unicorn", description: "Consumer food company." },
    { name: "ShareChat", industry: "Social Media", tier: "Unicorn", description: "Indian social media and networking service." },
    { name: "Dailyhunt", industry: "Content", tier: "Unicorn", description: "News and content aggregator application." },
    { name: "Glance", industry: "Content", tier: "Unicorn", description: "Lock screen content platform." },
    { name: "Digit Insurance", industry: "InsurTech", tier: "Unicorn", description: "General insurance company." },
    { name: "Innovaccer", industry: "HealthTech", tier: "Unicorn", description: "Healthcare technology company." },
    { name: "Infra.Market", industry: "PropTech", tier: "Unicorn", description: "Construction solutions company." },
    { name: "Five Star Business Finance", industry: "Fintech", tier: "Unicorn", description: "NBFC providing loans to small businesses." },
    { name: "FirstCry", industry: "E-commerce", tier: "Unicorn", description: "Online shopping for baby product." },
    { name: "BharatPe", industry: "Fintech", tier: "Unicorn", description: "Payments application for merchants." },
    { name: "MindTickle", industry: "SaaS", tier: "Unicorn", description: "Sales readiness platform." },
    { name: "upGrad", industry: "EdTech", tier: "Unicorn", description: "Higher education platform." },
    { name: "CoinDCX", industry: "Crypto", tier: "Unicorn", description: "Cryptocurrency exchange." },
    { name: "Eruditus", industry: "EdTech", tier: "Unicorn", description: "Executive education platform." },
    { name: "Zetwerk", industry: "B2B", tier: "Unicorn", description: "B2B manufacturing services marketplace." },
    { name: "Moglix", industry: "B2B", tier: "Unicorn", description: "B2B e-commerce platform for industrial tools." },
    { name: "Zeta", industry: "Fintech", tier: "Unicorn", description: "Modern banking tech stack provider." },
    { name: "BlackBuck", industry: "Logistics", tier: "Unicorn", description: "Trucking platform." },
    { name: "Droom", industry: "Auto Tech", tier: "Unicorn", description: "AI-driven marketplace for buying and selling used vehicles." },
    { name: "ChargeBee", industry: "SaaS", tier: "Unicorn", description: "Subscription billing software." },
    { name: "Gupshup", industry: "SaaS", tier: "Unicorn", description: "Conversational messaging platform." },
    { name: "Pine Labs", industry: "Fintech", tier: "Unicorn", description: "Merchant platform for payment solutions." },
    { name: "CitiusTech", industry: "HealthTech", tier: "Unicorn", description: "Healthcare technology services and solutions." },
    { name: "Icertis", industry: "SaaS", tier: "Unicorn", description: "Contract management software." },
    { name: "Ola Electric", industry: "EV", tier: "Unicorn", description: "Electric vehicle manufacturer." },
    { name: "Acko", industry: "InsurTech", tier: "Unicorn", description: "General insurance company." },
    { name: "Mobile Premier League", industry: "Gaming", tier: "Unicorn", description: "Mobile e-Sports platform." },
    { name: "Rebel Foods", industry: "Food Tech", tier: "Unicorn", description: "World's largest internet restaurant company." },
    { name: "Spinny", industry: "Auto Tech", tier: "Unicorn", description: "Used car retailing platform." },
    { name: "Upstox", industry: "Fintech", tier: "Unicorn", description: "Online discount brokerage firm." },
    { name: "Slice", industry: "Fintech", tier: "Unicorn", description: "Credit card challenger." },
    { name: "Pristyn Care", industry: "HealthTech", tier: "Unicorn", description: "Healthcare provider." },
    { name: "Mamaearth", industry: "D2C", tier: "Unicorn", description: "Natural personal care products." },
    { name: "GlobalBees", industry: "E-commerce", tier: "Unicorn", description: "Thrasio-style D2C roll-up brand." },
    { name: "Simpl", industry: "Fintech", tier: "Unicorn", description: "Pay later platform." },
    { name: "PhysicsWallah", industry: "EdTech", tier: "Unicorn", description: "Affordable education platform." },
    { name: "OneCard", industry: "Fintech", tier: "Unicorn", description: "Mobile-first credit card." },
    { name: "5ire", industry: "Web3", tier: "Unicorn", description: "Blockchain network." },
    { name: "Shiprocket", industry: "Logistics", tier: "Unicorn", description: "Shipping and logistics aggregator." },
    { name: "Tata 1mg", industry: "HealthTech", tier: "Unicorn", description: "Online pharmacy." },
];
