import { JobListing } from './job-service';

export const PINNED_INDIAN_INTERNSHIPS: JobListing[] = [
    {
        id: 'pinned-zoho-2026',
        title: 'Software Developer Intern - 2026 Batch',
        company: 'Zoho Corporation',
        link: 'https://careers.zohocorp.com/recruit/Portal.na',
        pubDate: new Date().toISOString(),
        source: 'Featured (Direct Apply)',
        snippet: 'Off-campus drive for Software Developer Interns (2026 Batch). Locations: Chennai, Coimbatore, Karaikudi, Tirunelveli. Skills: C, C++, Java.',
    },
    {
        id: 'pinned-ibm-intern',
        title: 'Software Developer Intern (Summer 2026)',
        company: 'IBM India',
        link: 'https://www.ibm.com/in-en/careers',
        pubDate: new Date().toISOString(),
        source: 'Featured (MNC)',
        snippet: 'Hiring 2026 batch for Summer Internships. Roles available in Bangalore, Hyderabad, and Gurgaon. Focus on Cloud and AI.',
    },
    {
        id: 'pinned-cisco-intern',
        title: 'Technical Intern - Standard (India)',
        company: 'Cisco',
        link: 'https://jobs.cisco.com/jobs/SearchJobs/India?21178=%5B%22207946%22%5D&21178_format=6020&listFilterMode=1',
        pubDate: new Date().toISOString(),
        source: 'Featured (MNC)',
        snippet: 'Cisco Ideaathon and General Internship hiring for 2026 passouts. Role: Software Engineer Intern. Location: Bangalore.',
    },
    {
        id: 'pinned-sprinklr-intern',
        title: 'Product Engineering Intern (Summer 2026)',
        company: 'Sprinklr',
        link: 'https://www.sprinklr.com/careers/',
        pubDate: new Date().toISOString(),
        source: 'Featured (Unicorn)',
        snippet: 'High paying internship opportunity for 2026 batch in Gurgaon/Bangalore. Role involves backend/frontend development.',
    },
    {
        id: 'pinned-qualcomm-intern',
        title: 'Interim Engineering Intern (HW/SW)',
        company: 'Qualcomm',
        link: 'https://qualcomm.wd5.myworkdayjobs.com/External',
        pubDate: new Date().toISOString(),
        source: 'Featured (Core)',
        snippet: 'Hiring for Summer 2026 internships. Locations: Bangalore, Hyderabad, Noida, Chennai. Eligible: CS, ECE, EEE.',
    },
    {
        id: 'pinned-accenture-summer',
        title: 'Summer Internship Program 2026',
        company: 'Accenture',
        link: 'https://www.accenture.com/in-en/careers/life-at-accenture/entry-level-careers-internships',
        pubDate: new Date().toISOString(),
        source: 'Featured (Service)',
        snippet: '8-12 weeks internship program for pre-final year students (2026 graduates). Technology and consulting roles.',
    },
    {
        id: 'pinned-hackerearth-challenges',
        title: 'Multiple Hiring Challenges (2026 Batch)',
        company: 'HackerEarth (Aggregator)',
        link: 'https://www.hackerearth.com/challenges/',
        pubDate: new Date().toISOString(),
        source: 'Hiring Drives',
        snippet: 'Various hiring challenges for 2026 batch including Zerve.AI and others. Participate to get direct interview calls.',
    },
    {
        id: 'pinned-siemens-intern',
        title: 'Software Engineer Intern (R&D)',
        company: 'Siemens',
        link: 'https://jobs.siemens.com/careers',
        pubDate: new Date().toISOString(),
        source: 'Featured (Core)',
        snippet: 'Research & Development internship openings in Noida and Bangalore for Computer Science students.',
    },
    {
        id: 'pinned-deshaw-intern',
        title: 'Software Engineering Intern',
        company: 'D. E. Shaw India',
        link: 'https://www.deshawindia.com/careers/internships',
        pubDate: new Date().toISOString(),
        source: 'Featured (Fintech)',
        snippet: 'Prestigious internship program for 2026 batch. Exceptional problem solving skills required. Stipend: High.',
    },
    {
        id: 'pinned-flipkart-runway',
        title: 'Flipkart Runway / Girls Wanna Code',
        company: 'Flipkart',
        link: 'https://www.flipkartcareers.com/',
        pubDate: new Date().toISOString(),
        source: 'Featured (Unicorn)',
        snippet: 'Upcoming internship drives for Summer 2026. Keep an eye out for Flipkart Runway program announcements.',
    }
];
